jobs:
  include:

    # Experimentation step
    - language: python
      python: "3.6"
      install:
        - pip install -r requirements.txt

      script:
        - python src/run_experiment.py ci-parameters.json
        - python src/generate_visualisations.py 60pop-1000evals-2runs-comment.csv

    # Testing step
    - language: python
      python: "3.6"
      install:
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -s src/ -p *.py
    
